### ISSUE TITLE
console.log instead of println

### ISSUE THREAD

**Issue by futuremarc** [shiffman/LearningProcessing-p5.js#1]
On line 22 [here](https://github.com/shiffman/LearningProcessing-p5.js/blob/master/chp04_variables/example_4_5_systemvars/sketch.js) should read console.log() not println()

**EDIT**: Ahh, I guess println() and print() are still a thing in p5. Is this something we want though? Shouldn't we be teaching console.log() only?

**Comment by shiffman** [comment]
Good question.  While maintaining compatibility with Processing code isn't a big priority it's nice ot have `println()` and `print()` for that purpose.  And, although these details seem tiny, the slightly friendlier language of `print` as well as not having the dot in `console.log` can help ease a beginner in.   For me though, this is a small detail and, yes, it's useful for students to see `console.log` behinds the scenes at some point.
