### ISSUE TITLE
Missing sunflower image chp15_07

### ISSUE THREAD

**Issue by mexitalian** [shiffman/LearningProcessing-p5.js#3]
The _data_ folder is missing for [chp15_images_pixels](https://github.com/shiffman/LearningProcessing-p5.js/tree/master/chp15_images_pixels/example_15_07_PixelArrayImage)'s example.
Are you happy to receive pull requests for such small modifications or would you prefer these submitted as issues?

**Comment by shiffman** [comment]
Yes, happy for pull requests!  Please file!  I should note I'd like to increase the resolution of these images (400x400?) and use [this public domain sunflower image](https://upload.wikimedia.org/wikipedia/commons/a/a9/A_sunflower.jpg).  I cropped it for the book as follows:

http://learningprocessing.com/code/assets/sunflower768.jpg
